### ISSUE TITLE
ByteBuffer methods don't work.

### ISSUE THREAD

**Issue by zm3y** [DoctorMcKay/node-tf2#9] opened 2015-07-28 17:07 UTC
1) I tested the new update and methods that use ByteBuffer do not work (such as trade, or delete). Protobufer methods work fine.
2) When gc send message, node-tf2 crash with "var msgName = type;"

**Comment by DoctorMcKay** [comment] 2015-07-28 17:24
1. What version are you using?
2. What do you mean by "do not work"? Do you get a crash? An error message? Nothing happens?
3. Can I get the full error message and stack trace?

**Comment by zm3y** [comment] 2015-07-28 17:34
1. node v0.12.7 / node-steam 1.0.0 / node-tf2 2.0.1
2. Nothing happens.
3. When gc send message:
Logged in!
loaded
/home/eva/test/node_modules/tf2/index.js:29
			var msgName = type;
			              ^
ReferenceError: type is not defined
    at SteamGameCoordinator.<anonymous> (/home/eva/test/node_modules/tf2/index.js:29:18)
    at SteamGameCoordinator.emit (events.js:118:17)
    at SteamGameCoordinator.handlers.(anonymous function) (/home/eva/test/node_modules/steam/lib/handlers/game_coordinator/index.js:104:10)
    at SteamGameCoordinator.<anonymous> (/home/eva/test/node_modules/steam/lib/handlers/game_coordinator/index.js:19:28)
    at SteamClient.emit (events.js:129:20)
    at SteamClient._netMsgReceived (/home/eva/test/node_modules/steam/lib/steam_client.js:182:10)
    at SteamClient.handlers.(anonymous function) (/home/eva/test/node_modules/steam/lib/steam_client.js:269:10)
    at SteamClient._netMsgReceived (/home/eva/test/node_modules/steam/lib/steam_client.js:167:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/home/eva/test/node_modules/steam/lib/connection.js:50:8)

**Comment by DoctorMcKay** [comment] 2015-07-28 17:41
The crash is pretty straightforward, I mistakenly reference an undefined variable on line 29 of index.js. As far as nothing happening when non-proto messages are sent, that's a bit more unclear. It's possible that the problem is in my code or in SteamGameCoordinator. My code looks fine to me at first glance though.

I'll fix this once I get a chance later on today.

**Comment by DoctorMcKay** [comment] 2015-07-28 21:35
The crash is fixed in v2.0.2. The other issues are caused by a node-steam bug for which I've submitted a pull request.

**Closed by DoctorMcKay** 2015-07-28 21:35 UTC
Labels: bug
